[build]
  command = "npm run build"
  publish = "out"
  base = ""

[context.production.environment]
  NODE_ENV = "production"

[context.production]
  command = "npm run build"

[context.production.environment]
  NODE_ENV = "production"
